Repository geoserver/geoserver-cloud, pull requests merged in 2023-04, with the labels that each got.

#315 Add prometheus exporter
  Makefile
  src/apps/infrastructure/gateway/pom.xml
  src/starters/webmvc/pom.xml
Labels: enhancement

#316 Remove useless contrib chart
  contrib/chart/.helmignore
  contrib/chart/Chart.yaml
  contrib/chart/requirements.yaml
  contrib/chart/templates/_helpers.tpl
  contrib/chart/templates/config/configmap.yaml
  contrib/chart/templates/config/deployment.yaml
  contrib/chart/templates/config/service.yaml
  contrib/chart/templates/discovery/deployment.yaml
  contrib/chart/templates/discovery/service.yaml
  contrib/chart/templates/gateway/deployment.yaml
  contrib/chart/templates/gateway/ingress.yaml
  contrib/chart/templates/gateway/service.yaml
  contrib/chart/templates/rest/deployment.yaml
  contrib/chart/templates/rest/service.yaml
  contrib/chart/templates/serviceaccount.yaml
  contrib/chart/templates/wcs/deployment.yaml
  contrib/chart/templates/wcs/service.yaml
  contrib/chart/templates/webui/deployment.yaml
  contrib/chart/templates/webui/service.yaml
  contrib/chart/templates/wfs/deployment.yaml
  contrib/chart/templates/wfs/service.yaml
  contrib/chart/templates/wms/deployment.yaml
  contrib/chart/templates/wms/service.yaml
  contrib/chart/values.yaml
Labels: enhancement

#321 Upgrade spring-boot:2.7.9 -> 2.7.10 with spring 5.3.25 -> 5.3.26
  src/pom.xml
Labels: build, dependencies

#322 Upgrade snakeyaml:1.30 -> 2.0, jackson:2.13.5 -> 2.14.2
  src/pom.xml
Labels: build, dependencies

#324 Fix GeoTools logging initialization not working with Logback
  src/catalog/backends/datadir/src/main/java/org/geoserver/cloud/config/catalog/backend/datadirectory/ParallelDataDirectoryGeoServerLoader.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/config/jndi/SimpleJNDIStaticContextInitializer.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/config/jndidatasource/JNDIDataSourceAutoConfiguration.java
  src/starters/webmvc/src/main/java/org/geoserver/cloud/autoconfigure/context/GeoServerContextInitializer.java
Labels: bug

#326 GWC Azure blob store throws exception initializing aws client
  src/catalog/backends/pom.xml
  src/catalog/catalog-server/pom.xml
  src/catalog/pom.xml
  src/gwc/core/src/main/java/org/geoserver/cloud/gwc/repository/ResourceStoreTileLayerCatalog.java
  src/pom.xml
  src/starters/catalog-backend/pom.xml
Labels: bug
