Repository geoserver/geoserver-cloud, pull requests merged in 2024-10, with the labels that each got.

#534 Upgrade GeoServer ACL to 2.3.1 for its multiplatform docker image
  compose/.env
  src/pom.xml
Labels: dependencies

#536 Add acceptance tests
  .github/workflows/pull-request.yaml
  Makefile
  acceptance_tests/.gitignore
  acceptance_tests/Dockerfile
  acceptance_tests/README.md
  acceptance_tests/entrypoint.py
  acceptance_tests/pyproject.toml
  acceptance_tests/tests/conftest.py
  acceptance_tests/tests/lib/utils.py
  acceptance_tests/tests/resources/getmap_expected.png
  acceptance_tests/tests/resources/labels/default_locale/default_value/language_None_expected.png
  acceptance_tests/tests/resources/labels/default_locale/default_value/language__expected.png
  acceptance_tests/tests/resources/labels/default_locale/default_value/language_de_expected.png
  acceptance_tests/tests/resources/labels/default_locale/default_value/language_fr_expected.png
  acceptance_tests/tests/resources/labels/default_locale/default_value/language_it_expected.png
  acceptance_tests/tests/resources/labels/default_locale/no_default_value/language_None_expected.png
  acceptance_tests/tests/resources/labels/default_locale/no_default_value/language__expected.png
  acceptance_tests/tests/resources/labels/default_locale/no_default_value/language_it_expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/default_value/language_None_expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/default_value/language__expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/default_value/language_de_expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/default_value/language_fr_expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/default_value/language_it_expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/no_default_value/language_None_expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/no_default_value/language__expected.png
  acceptance_tests/tests/resources/labels/no_default_locale/no_default_value/language_it_expected.png
  acceptance_tests/tests/resources/localized_labels.sld
  acceptance_tests/tests/resources/localized_no_default.sld
  acceptance_tests/tests/resources/localized_with_default.sld
  acceptance_tests/tests/resources/wfs_payload.xml
  acceptance_tests/tests/test_cascaded_stores.py
  acceptance_tests/tests/test_datastore.py
  acceptance_tests/tests/test_gwc.py
  acceptance_tests/tests/test_i18n.py
  acceptance_tests/tests/test_wfs.py
  acceptance_tests/tests/test_wms.py
  acceptance_tests/tests/test_workspace.py
  ci/requirements.txt
  compose/acceptance.yml
  compose/acceptance_pg_entrypoint/001_create_schemas.sql
  compose/compose.yml
Labels: enhancement, Code Sprint

#547 Docker build improvements
  .github/workflows/pull-request.yaml
  Makefile
  compose/.env
  compose/acceptance.yml
  compose/compose.yml
  compose/infra.yml
  docker-build/base-images-multiplatform.yml
  docker-build/base-images.yml
  docker-build/templates.yml
  src/apps/base-images/jre/Dockerfile
  src/apps/base-images/spring-boot/Dockerfile
  src/apps/geoserver/gwc/Dockerfile
  src/apps/geoserver/restconfig/Dockerfile
  src/apps/geoserver/wcs/Dockerfile
  src/apps/geoserver/webui/Dockerfile
  src/apps/geoserver/wfs/Dockerfile
  src/apps/geoserver/wms/Dockerfile
  src/apps/geoserver/wps/Dockerfile
  src/apps/infrastructure/admin/Dockerfile
  src/apps/infrastructure/config/Dockerfile
  src/apps/infrastructure/discovery/Dockerfile
  src/apps/infrastructure/gateway/Dockerfile
Labels: build, docker

#557 Install system CA certificates in base Docker image
  src/apps/base-images/jre/Dockerfile
Labels: enhancement, build, docker

#558 Speed up application startup times with AppCDS
  compose/compose.yml
  src/apps/base-images/jre/Dockerfile
  src/apps/base-images/spring-boot/Dockerfile
  src/apps/geoserver/gwc/Dockerfile
  src/apps/geoserver/restconfig/Dockerfile
  src/apps/geoserver/wcs/Dockerfile
  src/apps/geoserver/webui/Dockerfile
  src/apps/geoserver/wfs/Dockerfile
  src/apps/geoserver/wms/Dockerfile
  src/apps/geoserver/wps/Dockerfile
  src/apps/infrastructure/admin/Dockerfile
  src/apps/infrastructure/config/Dockerfile
  src/apps/infrastructure/discovery/Dockerfile
  src/apps/infrastructure/gateway/Dockerfile
  src/starters/spring-boot/src/main/java/org/geoserver/cloud/app/ExitOnApplicationEventAutoConfiguration.java
  src/starters/spring-boot/src/main/resources/META-INF/spring.factories
  src/starters/spring-boot/src/main/resources/gs_cloud_bootstrap_profiles.yml
Labels: enhancement, build, docker

#563 Workaround an issue where the JNDIInitializer would be called several times
  src/catalog/backends/common/src/main/java/org/geoserver/cloud/autoconfigure/catalog/backend/core/GeoServerBackendAutoConfiguration.java
  src/catalog/backends/pgconfig/src/main/java/org/geoserver/cloud/autoconfigure/catalog/backend/pgconfig/PgconfigDataSourceAutoConfiguration.java
  src/catalog/backends/pgconfig/src/main/java/org/geoserver/cloud/config/catalog/backend/pgconfig/PconfigDataSourceConfiguration.java
  src/catalog/backends/pgconfig/src/test/java/org/geoserver/cloud/backend/pgconfig/support/PgConfigTestContainer.java
  src/library/spring-boot-simplejndi/pom.xml
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/autoconfigure/jndi/JNDIDataSourceAutoConfiguration.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/autoconfigure/jndi/SimpleJNDIStaticContextInitializer.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/config/jndi/JNDIDataSourceConfiguration.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/config/jndi/JNDIDataSourcesConfigurationProperties.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/config/jndi/JNDIDatasourceConfig.java
  src/library/spring-boot-simplejndi/src/main/java/org/geoserver/cloud/config/jndi/JNDIInitializer.java
  src/library/spring-boot-simplejndi/src/main/resources/META-INF/spring.factories
  src/library/spring-boot-simplejndi/src/test/java/org/geoserver/cloud/autoconfigure/jndi/JNDIDataSourceAutoConfigurationTest.java
  src/library/spring-boot-simplejndi/src/test/java/org/geoserver/cloud/config/jndi/SimpleJNDIStaticContextInitializerTest.java
Labels: bugfix

#564 Add JDBC and LDAP security plugins
  README.md
  src/apps/geoserver/gwc/src/main/resources/bootstrap.yml
  src/apps/geoserver/restconfig/src/main/resources/bootstrap.yml
  src/apps/geoserver/wcs/src/main/resources/bootstrap.yml
  src/apps/geoserver/webui/pom.xml
  src/apps/geoserver/wfs/src/main/resources/bootstrap.yml
  src/pom.xml
  src/starters/security/pom.xml
  src/starters/security/src/main/java/org/geoserver/cloud/autoconfigure/security/jdbc/JDBCSecurityAutoConfiguration.java
  src/starters/security/src/main/java/org/geoserver/cloud/autoconfigure/security/jdbc/JDBCSecurityConfigProperties.java
  src/starters/security/src/main/java/org/geoserver/cloud/autoconfigure/security/jdbc/JDBCSecurityWebUIAutoConfiguration.java
  src/starters/security/src/main/java/org/geoserver/cloud/autoconfigure/security/ldap/LDAPSecurityAutoConfiguration.java
  src/starters/security/src/main/java/org/geoserver/cloud/autoconfigure/security/ldap/LDAPSecurityConfigProperties.java
  src/starters/security/src/main/java/org/geoserver/cloud/autoconfigure/security/ldap/LDAPSecurityWebUIAutoConfiguration.java
  src/starters/security/src/main/resources/META-INF/spring.factories
  src/starters/security/src/test/java/org/geoserver/cloud/autoconfigure/security/jdbc/JDBCSecurityAutoConfigurationTest.java
  src/starters/security/src/test/java/org/geoserver/cloud/autoconfigure/security/jdbc/JDBCSecurityWebUIAutoConfigurationTest.java
  src/starters/security/src/test/java/org/geoserver/cloud/autoconfigure/security/ldap/LDAPSecurityAutoConfigurationTest.java
  src/starters/security/src/test/java/org/geoserver/cloud/autoconfigure/security/ldap/LDAPSecurityWebUIAutoConfigurationTest.java
Labels: feature

#565 Fix saving workspace services not working with pgconfig
  compose/.env
  compose/compose.yml
  src/catalog/backends/pgconfig/src/main/resources/db/pgconfig/migration/postgresql/V1_8__ServiceInfoSettingsInfoConstraints.sql
  src/catalog/backends/pgconfig/src/test/java/org/geoserver/cloud/backend/pgconfig/config/PgconfigConfigRepositoryConformanceTest.java
  src/catalog/cache/src/main/java/org/geoserver/cloud/catalog/cache/CachingGeoServerFacade.java
Labels: bugfix

#566 Enable restconfig-wmts extension
  src/apps/geoserver/restconfig/pom.xml
Labels: feature

#567 Fix inconcistencies with caching GeoServer config infos
  src/catalog/cache/src/main/java/org/geoserver/cloud/catalog/cache/CachingGeoServerFacade.java
  src/catalog/cache/src/test/java/org/geoserver/cloud/catalog/cache/CachingGeoServerFacadeTest.java
Labels: bugfix

#569 Set default values for min/max heap memory percentage in the base JRE image
  compose/.env
  docs/deploy/docker-compose/stable/pgconfig/compose.yml
  src/apps/base-images/jre/Dockerfile
Labels: docker
